[package]
name = "rusty-release"
version = "0.2.3"
authors = ["Daniel Trstenjak <daniel.trstenjak@gmail.com>"]
license = "BSD-3-Clause"
description = "Make a release of a cargo project"
repository = "https://github.com/dan-t/rusty-release"
readme = "README.md"

[dependencies]
clap = "~2.2.4"
term = "~0.4.4"
tempfile = "~2.1.1"
toml = "~0.1.28"
semver = "~0.2.3"
rustc-serialize = "0.3.18"
