[package]
name = "rusty-release"
version = "0.3.6"
authors = ["Daniel Trstenjak <daniel.trstenjak@gmail.com>"]
license = "BSD-3-Clause"
description = "Make a release of a cargo project"
repository = "https://github.com/dan-t/rusty-release"
readme = "README.md"

[dependencies]
clap = "~2.2.6"
term = "~0.4.4"
tempfile = "~2.1.4"
toml = "~0.1.30"
semver = "~0.2.3"
rustc-serialize = "~0.3.19"
